pub const GRID_SIZE: f64 = 20.0;
pub const SMART_GUIDE_THRESHOLD: f64 = 8.0;
pub const EQUAL_SPACING_SNAP_RADIUS: f64 = GRID_SIZE * 40.0;
pub const ENDPOINT_SNAP_RADIUS: f64 = GRID_SIZE * 40.0;
pub const MULTI_MOVE_SNAP_RADIUS: f64 = GRID_SIZE * 20.0;
pub const ARROW_BIND_MIDPOINT_RADIUS: f64 = 30.0;
pub const ARROW_BIND_BORDER_RADIUS: f64 = 15.0;
