use astra_canvas::shapes::ShapeId;
use astra_canvas::tools::ToolKind;
use egui::Color32;

#[derive(Debug, Clone, PartialEq)]
pub enum UiAction {
    SetTool(ToolKind),
    SetStrokeColor(Color32),
    SetFillColor(Option<Color32>),
    SetStrokeWidth(f32),
    SaveLocal,
    SaveLocalAs,
    ShowOpenDialog,
    ShowOpenRecentDialog,
    SaveLocalWithName(String),
    LoadLocal(String),
    SaveDocument,
    LoadDocument,
    DownloadDocument,
    UploadDocument,
    ExportPng,
    CopyPng,
    ToggleGrid,
    ZoomIn,
    ZoomOut,
    ZoomReset,
    ToggleGridSnap,
    ToggleSmartSnap,
    ToggleAngleSnap,
    SetCornerRadius(f32),
    SetExportScale(u8),
    ClearDocument,
    SetSloppiness(u8),
    SetFillPattern(u8),
    SetPathStyle(u8),
    SetStrokeStyle(u8),
    Undo,
    Redo,
    SetBgColor(Color32),
    BringToFront,
    SendToBack,
    BringForward,
    SendBackward,
    ZoomToFit,
    Duplicate,
    CopyShapes,
    CutShapes,
    PasteShapes,
    AlignTop,
    AlignBottom,
    AlignLeft,
    AlignRight,
    AlignCenterH,
    AlignCenterV,
    SetOpacity(f32),
    UpdateMathLatex(ShapeId, String),
    SelectAll,
    DeleteSelected,
    GroupSelected,
    UngroupSelected,
    NudgeSelection(f64, f64),
    CopyText(String),
    RequestMathPaste,
    ToggleTheme,
    SetFontSize(f32),
}
